//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employeemanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public credential()
        {
            this.employeequalifications = new HashSet<employeequalification>();
        }
    
        public int credentialid { get; set; }
        public string degreename { get; set; }
        public string field { get; set; }
        public string major { get; set; }
        public string university { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeequalification> employeequalifications { get; set; }
    }
}
