//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employeemanagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeequalification
    {
        public int empid { get; set; }
        public int credentialid { get; set; }
        public byte[] proof { get; set; }
    
        public virtual credential credential { get; set; }
        public virtual employee employee { get; set; }
    }
}
