//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employeemanagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class University_AdministrationEntities1 : DbContext
    {
        public University_AdministrationEntities1()
            : base("name=University_AdministrationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<credential> credentials { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employeequalification> employeequalifications { get; set; }
    }
}
